
export const FETCH_SCAN_REQUEST = 'FETCH_SCAN_REQUEST';
export const FETCH_SCAN_SUCCESS = 'FETCH_SCAN_SUCCESS';
export const FETCH_SCAN_FAILURE = 'FETCH_SCAN_FAILURE';
export const FETCH_SCAN_SET_PAGE = 'FETCH_SCAN_SET_PAGE';
